name: CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: Node js 설정
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 의존성 설치
        run: npm ci

      - name: Build
        run : npm run build

      - name: AWS 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: S3 업로드
        run: |
          aws s3 sync ./dist s3://threadly-front-prod --delete

      - name: CourFront 캐시 삭제
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --path "/*
          
          
